name: Build APK with Flutter 3.32.7

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Flutter 3.32.7
        run: |
          git clone https://github.com/flutter/flutter.git --branch 3.32.7 --depth 1
          echo "$GITHUB_WORKSPACE/flutter/bin" >> $GITHUB_PATH
          export PATH="$GITHUB_WORKSPACE/flutter/bin:$PATH"
          flutter doctor
        shell: bash

      - name: Enable Flutter
        run: |
          export PATH="$GITHUB_WORKSPACE/flutter/bin:$PATH"
          flutter doctor
          flutter config --no-analytics
        shell: bash

      - name: Install dependencies
        run: |
          export PATH="$GITHUB_WORKSPACE/flutter/bin:$PATH"
          flutter pub get
        shell: bash

      - name: Build APK
        run: |
          export PATH="$GITHUB_WORKSPACE/flutter/bin:$PATH"
          flutter build apk --release
        shell: bash

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: build/app/outputs/flutter-apk/app-release.apk
